/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-23 14:28:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589015908000L));
    _jspx_dependants.put("jar:file:/C:/Users/berry/eclipse-workspace/aPlanner_2020/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aPlanner_2020/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/HTML;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

request.setCharacterEncoding("UTF-8");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"Yoga Studio Template\">\n");
      out.write("    <meta name=\"keywords\" content=\"Yoga, unica, creative, html\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("    <title>Violet | Template</title>\n");
      out.write("\n");
      out.write("    <!-- Google Font -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900&display=swap\"\n");
      out.write("        rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Css Styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/font-awesome.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/nice-select.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/owl.carousel.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/magnific-popup.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/slicknav.min.css\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/style.css\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <!-- Page Preloder -->\n");
      out.write("    <div id=\"preloder\">\n");
      out.write("        <div class=\"loader\"></div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Search model -->\n");
      out.write("\t<div class=\"search-model\">\n");
      out.write("\t\t<div class=\"h-100 d-flex align-items-center justify-content-center\">\n");
      out.write("\t\t\t<div class=\"search-close-switch\">+</div>\n");
      out.write("\t\t\t<form class=\"search-model-form\">\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Search model end -->\n");
      out.write("\n");
      out.write("    <!-- Header Section Begin -->\n");
      out.write("    <header class=\"header-section\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"inner-header\">\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <a href=\"./index.html\"><img src=\"resources/img/logo.png\" alt=\"\"></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"header-right\">\n");
      out.write("                    <img src=\"resources/img/icons/search.png\" alt=\"\" class=\"search-trigger\">\n");
      out.write("                    <img src=\"resources/img/icons/man.png\" alt=\"\">\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <img src=\"resources/img/icons/bag.png\" alt=\"\">\n");
      out.write("                        <span>2</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"user-access\">\n");
      out.write("                    <a href=\"#\">Register</a>\n");
      out.write("                    <a href=\"#\" class=\"in\">Sign in</a>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"main-menu mobile-menu\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a class=\"active\" href=\"./index.html\">Home</a></li>\n");
      out.write("                        <li><a href=\"./categories.html\">Shop</a>\n");
      out.write("                            <ul class=\"sub-menu\">\n");
      out.write("                                <li><a href=\"product-page.html\">Product Page</a></li>\n");
      out.write("                                <li><a href=\"shopping-cart.html\">Shopping Card</a></li>\n");
      out.write("                                <li><a href=\"check-out.html\">Check out</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"./product-page.html\">About</a></li>\n");
      out.write("                        <li><a href=\"./check-out.html\">Blog</a></li>\n");
      out.write("                        <li><a href=\"./contact.html\">Contact</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Header Info Begin -->\n");
      out.write("    <div class=\"header-info\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"header-item\">\n");
      out.write("                        <img src=\"resources/img/icons/delivery.png\" alt=\"\">\n");
      out.write("                        <p>Free shipping on orders over $30 in USA</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 text-left text-lg-center\">\n");
      out.write("                    <div class=\"header-item\">\n");
      out.write("                        <img src=\"resources/img/icons/voucher.png\" alt=\"\">\n");
      out.write("                        <p>20% Student Discount</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 text-left text-xl-right\">\n");
      out.write("                    <div class=\"header-item\">\n");
      out.write("                    <img src=\"resources/img/icons/sales.png\" alt=\"\">\n");
      out.write("                    <p>30% off on dresses. Use code: 30OFF</p>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Header Info End -->\n");
      out.write("    <!-- Header End -->\n");
      out.write("\n");
      out.write("    <!-- Hero Slider Begin -->\n");
      out.write("    <section class=\"hero-slider\">\n");
      out.write("        <div class=\"hero-items owl-carousel\">\n");
      out.write("            <div class=\"single-slider-item set-bg\" data-setbg=\"resources/img/slider-1.jpg\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <h1>2019</h1>\n");
      out.write("                            <h2>Lookbook.</h2>\n");
      out.write("                            <a href=\"#\" class=\"primary-btn\">See More</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"single-slider-item set-bg\" data-setbg=\"resources/img/slider-2.jpg\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <h1>2019</h1>\n");
      out.write("                            <h2>Lookbook.</h2>\n");
      out.write("                            <a href=\"#\" class=\"primary-btn\">See More</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"single-slider-item set-bg\" data-setbg=\"resources/img/slider-3.jpg\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <h1>2019</h1>\n");
      out.write("                            <h2>Lookbook.</h2>\n");
      out.write("                            <a href=\"#\" class=\"primary-btn\">See More</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Hero Slider End -->\n");
      out.write("\n");
      out.write("    <!-- Features Section Begin -->\n");
      out.write("    <section class=\"features-section spad\">\n");
      out.write("        <div class=\"features-ads\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <div class=\"single-features-ads first\">\n");
      out.write("                            <img src=\"resources/img/icons/f-delivery.png\" alt=\"\">\n");
      out.write("                            <h4>Free shipping</h4>\n");
      out.write("                            <p>Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal\n");
      out.write("                                esuada aliquet libero viverra cursus. </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <div class=\"single-features-ads second\">\n");
      out.write("                            <img src=\"resources/img/icons/coin.png\" alt=\"\">\n");
      out.write("                            <h4>100% Money back </h4>\n");
      out.write("                            <p>Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada\n");
      out.write("                                aliquet libero viverra cursus. </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-4\">\n");
      out.write("                        <div class=\"single-features-ads\">\n");
      out.write("                            <img src=\"resources/img/icons/chat.png\" alt=\"\">\n");
      out.write("                            <h4>Online support 24/7</h4>\n");
      out.write("                            <p>Urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vesti bulum mal esuada\n");
      out.write("                                aliquet libero viverra cursus. </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Features Box -->\n");
      out.write("        <div class=\"features-box\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-lg-12\">\n");
      out.write("                                <div class=\"single-box-item first-box\">\n");
      out.write("                                    <img src=\"resources/img/f-box-1.jpg\" alt=\"\">\n");
      out.write("                                    <div class=\"box-text\">\n");
      out.write("                                        <span class=\"trend-year\">2019 Party</span>\n");
      out.write("                                        <h2>Jewelry</h2>\n");
      out.write("                                        <span class=\"trend-alert\">Trend Allert</span>\n");
      out.write("                                        <a href=\"#\" class=\"primary-btn\">See More</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-12\">\n");
      out.write("                                <div class=\"single-box-item second-box\">\n");
      out.write("                                    <img src=\"resources/img/f-box-2.jpg\" alt=\"\">\n");
      out.write("                                    <div class=\"box-text\">\n");
      out.write("                                        <span class=\"trend-year\">2019 Trend</span>\n");
      out.write("                                        <h2>Footwear</h2>\n");
      out.write("                                        <span class=\"trend-alert\">Bold & Black</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-6\">\n");
      out.write("                        <div class=\"single-box-item large-box\">\n");
      out.write("                            <img src=\"resources/img/f-box-3.jpg\" alt=\"\">\n");
      out.write("                            <div class=\"box-text\">\n");
      out.write("                                <span class=\"trend-year\">2019 Party</span>\n");
      out.write("                                <h2>Collection</h2>\n");
      out.write("                                <div class=\"trend-alert\">Trend Allert</div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Features Section End -->\n");
      out.write("\n");
      out.write("    <!-- Latest Product Begin -->\n");
      out.write("    <section class=\"latest-products spad\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"product-filter\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-12 text-center\">\n");
      out.write("                        <div class=\"section-title\">\n");
      out.write("                            <h2>Latest Products</h2>\n");
      out.write("                        </div>\n");
      out.write("                        <ul class=\"product-controls\">\n");
      out.write("                            <li data-filter=\"*\">All</li>\n");
      out.write("                            <li data-filter=\".dresses\">Dresses</li>\n");
      out.write("                            <li data-filter=\".bags\">Bags</li>\n");
      out.write("                            <li data-filter=\".shoes\">Shoes</li>\n");
      out.write("                            <li data-filter=\".accesories\">Accesories</li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\" id=\"product-list\">\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all dresses bags\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-1.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status\">new</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Green Dress with details</h6>\n");
      out.write("                            <p>$22.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all dresses bags\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-2.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status sale\">sale</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Yellow Maxi Dress</h6>\n");
      out.write("                            <p>$25.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all shoes accesories\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-3.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status\">new</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>One piece bodysuit</h6>\n");
      out.write("                            <p>$19.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all shoes accesories\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-4.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status popular\">popular</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Blue Dress with details</h6>\n");
      out.write("                            <p>$35.50</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all dresses shoes\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-5.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status\">new</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Green Dress with details</h6>\n");
      out.write("                            <p>$22.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all accesories bags\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-6.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status sale\">sale</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Yellow Maxi Dress</h6>\n");
      out.write("                            <p>$25.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all dresses bags\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-7.jpg\" alt=\"\"></a>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>One piece bodysuit</h6>\n");
      out.write("                            <p>$19.90</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mix all accesories bags\">\n");
      out.write("                    <div class=\"single-product-item\">\n");
      out.write("                        <figure>\n");
      out.write("                            <a href=\"#\"><img src=\"resources/img/products/img-8.jpg\" alt=\"\"></a>\n");
      out.write("                            <div class=\"p-status popular\">popular</div>\n");
      out.write("                        </figure>\n");
      out.write("                        <div class=\"product-text\">\n");
      out.write("                            <h6>Blue Dress with details</h6>\n");
      out.write("                            <p>$35.50</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Latest Product End -->\n");
      out.write("\n");
      out.write("    <!-- Lookbok Section Begin -->\n");
      out.write("    <section class=\"lookbok-section\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-4 offset-lg-1\">\n");
      out.write("                    <div class=\"lookbok-left\">\n");
      out.write("                        <div class=\"section-title\">\n");
      out.write("                            <h2>2019 <br />#lookbook</h2>\n");
      out.write("                        </div>\n");
      out.write("                        <p>Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Vestibulum malesuada\n");
      out.write("                            aliquet libero viverra cursus. Aliquam erat volutpat. Morbi id dictum quam, ut commodo\n");
      out.write("                            lorem. In at nisi nec arcu porttitor aliquet vitae at dui. Sed sollicitudin nulla non leo\n");
      out.write("                            viverra scelerisque. Phasellus facilisis lobortis metus, sit amet viverra lectus finibus ac.\n");
      out.write("                            Aenean non felis dapibus, placerat libero auctor, ornare ante. Morbi quis ex eleifend,\n");
      out.write("                            sodales nulla vitae, scelerisque ante. Nunc id vulputate dui. Suspendisse consectetur rutrum\n");
      out.write("                            metus nec scelerisque. s</p>\n");
      out.write("                        <a href=\"#\" class=\"primary-btn look-btn\">See More</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-5 offset-lg-1\">\n");
      out.write("                    <div class=\"lookbok-pic\">\n");
      out.write("                        <img src=\"resources/img/lookbok.jpg\" alt=\"\">\n");
      out.write("                        <div class=\"pic-text\">fashion</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- Lookbok Section End -->\n");
      out.write("\n");
      out.write("    <!-- Logo Section Begin -->\n");
      out.write("    <div class=\"logo-section spad\">\n");
      out.write("        <div class=\"logo-items owl-carousel\">\n");
      out.write("            <div class=\"logo-item\">\n");
      out.write("                <img src=\"resources/img/logos/logo-1.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"logo-item\">\n");
      out.write("                <img src=\"resources/img/logos/logo-2.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"logo-item\">\n");
      out.write("                <img src=\"resources/img/logos/logo-3.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"logo-item\">\n");
      out.write("                <img src=\"resources/img/logos/logo-4.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"logo-item\">\n");
      out.write("                <img src=\"resources/img/logos/logo-5.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Logo Section End -->\n");
      out.write("\n");
      out.write("    <!-- Footer Section Begin -->\n");
      out.write("    <footer class=\"footer-section spad\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"newslatter-form\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-12\">\n");
      out.write("                        <form action=\"#\">\n");
      out.write("                            <input type=\"text\" placeholder=\"Your email address\">\n");
      out.write("                            <button type=\"submit\">Subscribe to our newsletter</button>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-widget\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h4>About us</h4>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>About Us</li>\n");
      out.write("                                <li>Community</li>\n");
      out.write("                                <li>Jobs</li>\n");
      out.write("                                <li>Shipping</li>\n");
      out.write("                                <li>Contact Us</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h4>Customer Care</h4>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>Search</li>\n");
      out.write("                                <li>Privacy Policy</li>\n");
      out.write("                                <li>2019 Lookbook</li>\n");
      out.write("                                <li>Shipping & Delivery</li>\n");
      out.write("                                <li>Gallery</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h4>Our Services</h4>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>Free Shipping</li>\n");
      out.write("                                <li>Free Returnes</li>\n");
      out.write("                                <li>Our Franchising</li>\n");
      out.write("                                <li>Terms and conditions</li>\n");
      out.write("                                <li>Privacy Policy</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                        <div class=\"single-footer-widget\">\n");
      out.write("                            <h4>Information</h4>\n");
      out.write("                            <ul>\n");
      out.write("                                <li>Payment methods</li>\n");
      out.write("                                <li>Times and shipping costs</li>\n");
      out.write("                                <li>Product Returns</li>\n");
      out.write("                                <li>Shipping methods</li>\n");
      out.write("                                <li>Conformity of the products</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"social-links-warp\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"social-links\">\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"instagram\"><i class=\"fa fa-instagram\"></i><span>instagram</span></a>\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"pinterest\"><i class=\"fa fa-pinterest\"></i><span>pinterest</span></a>\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"facebook\"><i class=\"fa fa-facebook\"></i><span>facebook</span></a>\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"twitter\"><i class=\"fa fa-twitter\"></i><span>twitter</span></a>\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"youtube\"><i class=\"fa fa-youtube\"></i><span>youtube</span></a>\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"tumblr\"><i class=\"fa fa-tumblr-square\"></i><span>tumblr</span></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("<div class=\"container text-center pt-5\">\n");
      out.write("                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- Footer Section End -->\n");
      out.write("\n");
      out.write("    <!-- Js Plugins -->\n");
      out.write("    <script src=\"resources/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/jquery.slicknav.js\"></script>\n");
      out.write("    <script src=\"resources/js/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/jquery.nice-select.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/mixitup.min.js\"></script>\n");
      out.write("    <script src=\"resources/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
